# Generated by Django 5.0.2 on 2024-03-12 15:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0002_post_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="last_score_update",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
